# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8d31a728c721545cbcf19c96e35dd8602f5c1dc39420bb882ee11e0e3db35acc04f0b8e1c692e2f240278a35970e78ae94ff2ec0143d656c37568c7ee8d13ef

test:
  secret_key_base: 4daddc548ed97fb80c10959d3233e2b71c466d1cd267c66d352ae31c90913fa0eb62aab11d715ff10c1cc848ec1d9e09183aee865f633c3a4748d04d3f6b151e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
